/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>star_marines_bot</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GameStatusRecord> GAME_STATUS_PKEY = UniqueKeys0.GAME_STATUS_PKEY;
	public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GamesRecord> GAME_PKEY = UniqueKeys0.GAME_PKEY;
	public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GamesRecord> GAME_TITLE_UC = UniqueKeys0.GAME_TITLE_UC;
	public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GamesUsersRecord> GAME_USER_PKEY = UniqueKeys0.GAME_USER_PKEY;
	public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.PlanetsRecord> PLANET_PKEY = UniqueKeys0.PLANET_PKEY;
	public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord> RELATION_PKEY = UniqueKeys0.RELATION_PKEY;
	public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UserGameStatusRecord> USER_GAME_STATUS_PKEY = UniqueKeys0.USER_GAME_STATUS_PKEY;
	public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersRecord> USER_PKEY = UniqueKeys0.USER_PKEY;
	public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersRecord> USER_LOGIN_KEY = UniqueKeys0.USER_LOGIN_KEY;
	public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersStepsRecord> USERS_STEPS_PKEY = UniqueKeys0.USERS_STEPS_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.GamesRecord, org.jooq.db.generate.tables.records.GameStatusRecord> GAMES__GAME_STATUS_FKEY = ForeignKeys0.GAMES__GAME_STATUS_FKEY;
	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.GamesUsersRecord, org.jooq.db.generate.tables.records.GamesRecord> GAMES_USERS__GAME_USER_GAME_ID_FKEY = ForeignKeys0.GAMES_USERS__GAME_USER_GAME_ID_FKEY;
	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.GamesUsersRecord, org.jooq.db.generate.tables.records.UsersRecord> GAMES_USERS__GAME_USER_USER_ID_FKEY = ForeignKeys0.GAMES_USERS__GAME_USER_USER_ID_FKEY;
	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.GamesUsersRecord, org.jooq.db.generate.tables.records.UserGameStatusRecord> GAMES_USERS__USER_GAME_STATUS_FKEY = ForeignKeys0.GAMES_USERS__USER_GAME_STATUS_FKEY;
	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRecord, org.jooq.db.generate.tables.records.UsersRecord> PLANETS__PLANETS_OWNER_ID_FKEY = ForeignKeys0.PLANETS__PLANETS_OWNER_ID_FKEY;
	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, org.jooq.db.generate.tables.records.PlanetsRecord> PLANETS_RELATIONS__PLANETS_RELATIONS_ANCESTOR_ID_FKEY = ForeignKeys0.PLANETS_RELATIONS__PLANETS_RELATIONS_ANCESTOR_ID_FKEY;
	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, org.jooq.db.generate.tables.records.PlanetsRecord> PLANETS_RELATIONS__PLANETS_RELATIONS_DESCENDANT_ID_FKEY = ForeignKeys0.PLANETS_RELATIONS__PLANETS_RELATIONS_DESCENDANT_ID_FKEY;
	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, org.jooq.db.generate.tables.records.GamesRecord> PLANETS_RELATIONS__PLANETS_RELATIONS_GAME_ID_FKEY = ForeignKeys0.PLANETS_RELATIONS__PLANETS_RELATIONS_GAME_ID_FKEY;
	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.UsersStepsRecord, org.jooq.db.generate.tables.records.PlanetsRecord> USERS_STEPS__USERS_STEPS_FORM_FKEY = ForeignKeys0.USERS_STEPS__USERS_STEPS_FORM_FKEY;
	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.UsersStepsRecord, org.jooq.db.generate.tables.records.PlanetsRecord> USERS_STEPS__USERS_STEPS_TO_FKEY = ForeignKeys0.USERS_STEPS__USERS_STEPS_TO_FKEY;
	public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.UsersStepsRecord, org.jooq.db.generate.tables.records.UsersRecord> USERS_STEPS__USERS_STEPS_USER_ID_FKEY = ForeignKeys0.USERS_STEPS__USERS_STEPS_USER_ID_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GameStatusRecord> GAME_STATUS_PKEY = createUniqueKey(org.jooq.db.generate.tables.GameStatus.GAME_STATUS, org.jooq.db.generate.tables.GameStatus.GAME_STATUS.GAME_STATUS_ID);
		public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GamesRecord> GAME_PKEY = createUniqueKey(org.jooq.db.generate.tables.Games.GAMES, org.jooq.db.generate.tables.Games.GAMES.GAME_ID);
		public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GamesRecord> GAME_TITLE_UC = createUniqueKey(org.jooq.db.generate.tables.Games.GAMES, org.jooq.db.generate.tables.Games.GAMES.TITLE);
		public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GamesUsersRecord> GAME_USER_PKEY = createUniqueKey(org.jooq.db.generate.tables.GamesUsers.GAMES_USERS, org.jooq.db.generate.tables.GamesUsers.GAMES_USERS.GAME_ID, org.jooq.db.generate.tables.GamesUsers.GAMES_USERS.USER_ID);
		public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.PlanetsRecord> PLANET_PKEY = createUniqueKey(org.jooq.db.generate.tables.Planets.PLANETS, org.jooq.db.generate.tables.Planets.PLANETS.PLANET_ID);
		public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord> RELATION_PKEY = createUniqueKey(org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS, org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS.RELATION_ID);
		public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UserGameStatusRecord> USER_GAME_STATUS_PKEY = createUniqueKey(org.jooq.db.generate.tables.UserGameStatus.USER_GAME_STATUS, org.jooq.db.generate.tables.UserGameStatus.USER_GAME_STATUS.USER_STATUS_ID);
		public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersRecord> USER_PKEY = createUniqueKey(org.jooq.db.generate.tables.Users.USERS, org.jooq.db.generate.tables.Users.USERS.USER_ID);
		public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersRecord> USER_LOGIN_KEY = createUniqueKey(org.jooq.db.generate.tables.Users.USERS, org.jooq.db.generate.tables.Users.USERS.LOGIN);
		public static final org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersStepsRecord> USERS_STEPS_PKEY = createUniqueKey(org.jooq.db.generate.tables.UsersSteps.USERS_STEPS, org.jooq.db.generate.tables.UsersSteps.USERS_STEPS.STEP_ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.GamesRecord, org.jooq.db.generate.tables.records.GameStatusRecord> GAMES__GAME_STATUS_FKEY = createForeignKey(org.jooq.db.generate.Keys.GAME_STATUS_PKEY, org.jooq.db.generate.tables.Games.GAMES, org.jooq.db.generate.tables.Games.GAMES.GAME_STATUS_ID);
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.GamesUsersRecord, org.jooq.db.generate.tables.records.GamesRecord> GAMES_USERS__GAME_USER_GAME_ID_FKEY = createForeignKey(org.jooq.db.generate.Keys.GAME_PKEY, org.jooq.db.generate.tables.GamesUsers.GAMES_USERS, org.jooq.db.generate.tables.GamesUsers.GAMES_USERS.GAME_ID);
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.GamesUsersRecord, org.jooq.db.generate.tables.records.UsersRecord> GAMES_USERS__GAME_USER_USER_ID_FKEY = createForeignKey(org.jooq.db.generate.Keys.USER_PKEY, org.jooq.db.generate.tables.GamesUsers.GAMES_USERS, org.jooq.db.generate.tables.GamesUsers.GAMES_USERS.USER_ID);
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.GamesUsersRecord, org.jooq.db.generate.tables.records.UserGameStatusRecord> GAMES_USERS__USER_GAME_STATUS_FKEY = createForeignKey(org.jooq.db.generate.Keys.USER_GAME_STATUS_PKEY, org.jooq.db.generate.tables.GamesUsers.GAMES_USERS, org.jooq.db.generate.tables.GamesUsers.GAMES_USERS.USER_STATUS_ID);
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRecord, org.jooq.db.generate.tables.records.UsersRecord> PLANETS__PLANETS_OWNER_ID_FKEY = createForeignKey(org.jooq.db.generate.Keys.USER_PKEY, org.jooq.db.generate.tables.Planets.PLANETS, org.jooq.db.generate.tables.Planets.PLANETS.OWNER_ID);
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, org.jooq.db.generate.tables.records.PlanetsRecord> PLANETS_RELATIONS__PLANETS_RELATIONS_ANCESTOR_ID_FKEY = createForeignKey(org.jooq.db.generate.Keys.PLANET_PKEY, org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS, org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS.ANCESTOR_ID);
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, org.jooq.db.generate.tables.records.PlanetsRecord> PLANETS_RELATIONS__PLANETS_RELATIONS_DESCENDANT_ID_FKEY = createForeignKey(org.jooq.db.generate.Keys.PLANET_PKEY, org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS, org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS.DESCENDANT_ID);
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, org.jooq.db.generate.tables.records.GamesRecord> PLANETS_RELATIONS__PLANETS_RELATIONS_GAME_ID_FKEY = createForeignKey(org.jooq.db.generate.Keys.GAME_PKEY, org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS, org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS.GAME_ID);
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.UsersStepsRecord, org.jooq.db.generate.tables.records.PlanetsRecord> USERS_STEPS__USERS_STEPS_FORM_FKEY = createForeignKey(org.jooq.db.generate.Keys.PLANET_PKEY, org.jooq.db.generate.tables.UsersSteps.USERS_STEPS, org.jooq.db.generate.tables.UsersSteps.USERS_STEPS.FROM);
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.UsersStepsRecord, org.jooq.db.generate.tables.records.PlanetsRecord> USERS_STEPS__USERS_STEPS_TO_FKEY = createForeignKey(org.jooq.db.generate.Keys.PLANET_PKEY, org.jooq.db.generate.tables.UsersSteps.USERS_STEPS, org.jooq.db.generate.tables.UsersSteps.USERS_STEPS.TO);
		public static final org.jooq.ForeignKey<org.jooq.db.generate.tables.records.UsersStepsRecord, org.jooq.db.generate.tables.records.UsersRecord> USERS_STEPS__USERS_STEPS_USER_ID_FKEY = createForeignKey(org.jooq.db.generate.Keys.USER_PKEY, org.jooq.db.generate.tables.UsersSteps.USERS_STEPS, org.jooq.db.generate.tables.UsersSteps.USERS_STEPS.USER_ID);
	}
}
