/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in star_marines_bot
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>star_marines_bot.s_game_id</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> S_GAME_ID = new org.jooq.impl.SequenceImpl<java.lang.Long>("s_game_id", org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>star_marines_bot.s_planet_id</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> S_PLANET_ID = new org.jooq.impl.SequenceImpl<java.lang.Long>("s_planet_id", org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>star_marines_bot.s_relation_id</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> S_RELATION_ID = new org.jooq.impl.SequenceImpl<java.lang.Long>("s_relation_id", org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>star_marines_bot.s_step_id</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> S_STEP_ID = new org.jooq.impl.SequenceImpl<java.lang.Long>("s_step_id", org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>star_marines_bot.s_user_id</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> S_USER_ID = new org.jooq.impl.SequenceImpl<java.lang.Long>("s_user_id", org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
