/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StarMarinesBot extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -755156151;

	/**
	 * The singleton instance of <code>star_marines_bot</code>
	 */
	public static final StarMarinesBot STAR_MARINES_BOT = new StarMarinesBot();

	/**
	 * No further instances allowed
	 */
	private StarMarinesBot() {
		super("star_marines_bot");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			org.jooq.db.generate.Sequences.S_GAME_ID,
			org.jooq.db.generate.Sequences.S_PLANET_ID,
			org.jooq.db.generate.Sequences.S_RELATION_ID,
			org.jooq.db.generate.Sequences.S_STEP_ID,
			org.jooq.db.generate.Sequences.S_USER_ID);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.jooq.db.generate.tables.GameStatus.GAME_STATUS,
			org.jooq.db.generate.tables.Games.GAMES,
			org.jooq.db.generate.tables.GamesUsers.GAMES_USERS,
			org.jooq.db.generate.tables.Planets.PLANETS,
			org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS,
			org.jooq.db.generate.tables.UserGameStatus.USER_GAME_STATUS,
			org.jooq.db.generate.tables.Users.USERS,
			org.jooq.db.generate.tables.UsersSteps.USERS_STEPS);
	}
}
