/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in star_marines_bot
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table star_marines_bot.game_status
	 */
	public static final org.jooq.db.generate.tables.GameStatus GAME_STATUS = org.jooq.db.generate.tables.GameStatus.GAME_STATUS;

	/**
	 * The table star_marines_bot.games
	 */
	public static final org.jooq.db.generate.tables.Games GAMES = org.jooq.db.generate.tables.Games.GAMES;

	/**
	 * The table star_marines_bot.games_users
	 */
	public static final org.jooq.db.generate.tables.GamesUsers GAMES_USERS = org.jooq.db.generate.tables.GamesUsers.GAMES_USERS;

	/**
	 * The table star_marines_bot.planets
	 */
	public static final org.jooq.db.generate.tables.Planets PLANETS = org.jooq.db.generate.tables.Planets.PLANETS;

	/**
	 * The table star_marines_bot.planets_relations
	 */
	public static final org.jooq.db.generate.tables.PlanetsRelations PLANETS_RELATIONS = org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS;

	/**
	 * The table star_marines_bot.user_game_status
	 */
	public static final org.jooq.db.generate.tables.UserGameStatus USER_GAME_STATUS = org.jooq.db.generate.tables.UserGameStatus.USER_GAME_STATUS;

	/**
	 * The table star_marines_bot.users
	 */
	public static final org.jooq.db.generate.tables.Users USERS = org.jooq.db.generate.tables.Users.USERS;

	/**
	 * The table star_marines_bot.users_steps
	 */
	public static final org.jooq.db.generate.tables.UsersSteps USERS_STEPS = org.jooq.db.generate.tables.UsersSteps.USERS_STEPS;
}
