/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameStatus extends org.jooq.impl.TableImpl<org.jooq.db.generate.tables.records.GameStatusRecord> {

	private static final long serialVersionUID = 1670879726;

	/**
	 * The singleton instance of <code>star_marines_bot.game_status</code>
	 */
	public static final org.jooq.db.generate.tables.GameStatus GAME_STATUS = new org.jooq.db.generate.tables.GameStatus();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.db.generate.tables.records.GameStatusRecord> getRecordType() {
		return org.jooq.db.generate.tables.records.GameStatusRecord.class;
	}

	/**
	 * The column <code>star_marines_bot.game_status.game_status_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.GameStatusRecord, java.lang.Short> GAME_STATUS_ID = createField("game_status_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>star_marines_bot.game_status.title</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.GameStatusRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * Create a <code>star_marines_bot.game_status</code> table reference
	 */
	public GameStatus() {
		this("game_status", null);
	}

	/**
	 * Create an aliased <code>star_marines_bot.game_status</code> table reference
	 */
	public GameStatus(java.lang.String alias) {
		this(alias, org.jooq.db.generate.tables.GameStatus.GAME_STATUS);
	}

	private GameStatus(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.GameStatusRecord> aliased) {
		this(alias, aliased, null);
	}

	private GameStatus(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.GameStatusRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GameStatusRecord> getPrimaryKey() {
		return org.jooq.db.generate.Keys.GAME_STATUS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GameStatusRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GameStatusRecord>>asList(org.jooq.db.generate.Keys.GAME_STATUS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.db.generate.tables.GameStatus as(java.lang.String alias) {
		return new org.jooq.db.generate.tables.GameStatus(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.jooq.db.generate.tables.GameStatus rename(java.lang.String name) {
		return new org.jooq.db.generate.tables.GameStatus(name, null);
	}
}
