/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Games extends org.jooq.impl.TableImpl<org.jooq.db.generate.tables.records.GamesRecord> {

	private static final long serialVersionUID = -1833284351;

	/**
	 * The singleton instance of <code>star_marines_bot.games</code>
	 */
	public static final org.jooq.db.generate.tables.Games GAMES = new org.jooq.db.generate.tables.Games();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.db.generate.tables.records.GamesRecord> getRecordType() {
		return org.jooq.db.generate.tables.records.GamesRecord.class;
	}

	/**
	 * The column <code>star_marines_bot.games.game_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.GamesRecord, java.lang.Long> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>star_marines_bot.games.title</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.GamesRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>star_marines_bot.games.game_status_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.GamesRecord, java.lang.Short> GAME_STATUS_ID = createField("game_status_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * Create a <code>star_marines_bot.games</code> table reference
	 */
	public Games() {
		this("games", null);
	}

	/**
	 * Create an aliased <code>star_marines_bot.games</code> table reference
	 */
	public Games(java.lang.String alias) {
		this(alias, org.jooq.db.generate.tables.Games.GAMES);
	}

	private Games(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.GamesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Games(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.GamesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GamesRecord> getPrimaryKey() {
		return org.jooq.db.generate.Keys.GAME_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GamesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.GamesRecord>>asList(org.jooq.db.generate.Keys.GAME_PKEY, org.jooq.db.generate.Keys.GAME_TITLE_UC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.db.generate.tables.records.GamesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.db.generate.tables.records.GamesRecord, ?>>asList(org.jooq.db.generate.Keys.GAMES__GAME_STATUS_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.db.generate.tables.Games as(java.lang.String alias) {
		return new org.jooq.db.generate.tables.Games(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.jooq.db.generate.tables.Games rename(java.lang.String name) {
		return new org.jooq.db.generate.tables.Games(name, null);
	}
}
