/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetsRelations extends org.jooq.impl.TableImpl<org.jooq.db.generate.tables.records.PlanetsRelationsRecord> {

	private static final long serialVersionUID = -931542386;

	/**
	 * The singleton instance of <code>star_marines_bot.planets_relations</code>
	 */
	public static final org.jooq.db.generate.tables.PlanetsRelations PLANETS_RELATIONS = new org.jooq.db.generate.tables.PlanetsRelations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.db.generate.tables.records.PlanetsRelationsRecord> getRecordType() {
		return org.jooq.db.generate.tables.records.PlanetsRelationsRecord.class;
	}

	/**
	 * The column <code>star_marines_bot.planets_relations.relation_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, java.lang.Long> RELATION_ID = createField("relation_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>star_marines_bot.planets_relations.ancestor_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, java.lang.Long> ANCESTOR_ID = createField("ancestor_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>star_marines_bot.planets_relations.descendant_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, java.lang.Long> DESCENDANT_ID = createField("descendant_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>star_marines_bot.planets_relations.game_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, java.lang.Long> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>star_marines_bot.planets_relations</code> table reference
	 */
	public PlanetsRelations() {
		this("planets_relations", null);
	}

	/**
	 * Create an aliased <code>star_marines_bot.planets_relations</code> table reference
	 */
	public PlanetsRelations(java.lang.String alias) {
		this(alias, org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS);
	}

	private PlanetsRelations(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.PlanetsRelationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private PlanetsRelations(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.PlanetsRelationsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord> getPrimaryKey() {
		return org.jooq.db.generate.Keys.RELATION_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord>>asList(org.jooq.db.generate.Keys.RELATION_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRelationsRecord, ?>>asList(org.jooq.db.generate.Keys.PLANETS_RELATIONS__PLANETS_RELATIONS_ANCESTOR_ID_FKEY, org.jooq.db.generate.Keys.PLANETS_RELATIONS__PLANETS_RELATIONS_DESCENDANT_ID_FKEY, org.jooq.db.generate.Keys.PLANETS_RELATIONS__PLANETS_RELATIONS_GAME_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.db.generate.tables.PlanetsRelations as(java.lang.String alias) {
		return new org.jooq.db.generate.tables.PlanetsRelations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.jooq.db.generate.tables.PlanetsRelations rename(java.lang.String name) {
		return new org.jooq.db.generate.tables.PlanetsRelations(name, null);
	}
}
