/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Planets extends org.jooq.impl.TableImpl<org.jooq.db.generate.tables.records.PlanetsRecord> {

	private static final long serialVersionUID = -744965544;

	/**
	 * The singleton instance of <code>star_marines_bot.planets</code>
	 */
	public static final org.jooq.db.generate.tables.Planets PLANETS = new org.jooq.db.generate.tables.Planets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.db.generate.tables.records.PlanetsRecord> getRecordType() {
		return org.jooq.db.generate.tables.records.PlanetsRecord.class;
	}

	/**
	 * The column <code>star_marines_bot.planets.planet_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.PlanetsRecord, java.lang.Long> PLANET_ID = createField("planet_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>star_marines_bot.planets.units</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.PlanetsRecord, java.lang.Integer> UNITS = createField("units", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>star_marines_bot.planets.max_units</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.PlanetsRecord, java.lang.Integer> MAX_UNITS = createField("max_units", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>star_marines_bot.planets.owner_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.PlanetsRecord, java.lang.Long> OWNER_ID = createField("owner_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>star_marines_bot.planets.game_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.PlanetsRecord, java.lang.Long> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>star_marines_bot.planets</code> table reference
	 */
	public Planets() {
		this("planets", null);
	}

	/**
	 * Create an aliased <code>star_marines_bot.planets</code> table reference
	 */
	public Planets(java.lang.String alias) {
		this(alias, org.jooq.db.generate.tables.Planets.PLANETS);
	}

	private Planets(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.PlanetsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Planets(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.PlanetsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.db.generate.tables.records.PlanetsRecord> getPrimaryKey() {
		return org.jooq.db.generate.Keys.PLANET_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.PlanetsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.PlanetsRecord>>asList(org.jooq.db.generate.Keys.PLANET_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.db.generate.tables.records.PlanetsRecord, ?>>asList(org.jooq.db.generate.Keys.PLANETS__PLANETS_OWNER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.db.generate.tables.Planets as(java.lang.String alias) {
		return new org.jooq.db.generate.tables.Planets(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.jooq.db.generate.tables.Planets rename(java.lang.String name) {
		return new org.jooq.db.generate.tables.Planets(name, null);
	}
}
