/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGameStatus extends org.jooq.impl.TableImpl<org.jooq.db.generate.tables.records.UserGameStatusRecord> {

	private static final long serialVersionUID = 2038399977;

	/**
	 * The singleton instance of <code>star_marines_bot.user_game_status</code>
	 */
	public static final org.jooq.db.generate.tables.UserGameStatus USER_GAME_STATUS = new org.jooq.db.generate.tables.UserGameStatus();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.db.generate.tables.records.UserGameStatusRecord> getRecordType() {
		return org.jooq.db.generate.tables.records.UserGameStatusRecord.class;
	}

	/**
	 * The column <code>star_marines_bot.user_game_status.user_status_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.UserGameStatusRecord, java.lang.Short> USER_STATUS_ID = createField("user_status_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>star_marines_bot.user_game_status.title</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.UserGameStatusRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * Create a <code>star_marines_bot.user_game_status</code> table reference
	 */
	public UserGameStatus() {
		this("user_game_status", null);
	}

	/**
	 * Create an aliased <code>star_marines_bot.user_game_status</code> table reference
	 */
	public UserGameStatus(java.lang.String alias) {
		this(alias, org.jooq.db.generate.tables.UserGameStatus.USER_GAME_STATUS);
	}

	private UserGameStatus(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.UserGameStatusRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserGameStatus(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.UserGameStatusRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UserGameStatusRecord> getPrimaryKey() {
		return org.jooq.db.generate.Keys.USER_GAME_STATUS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UserGameStatusRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UserGameStatusRecord>>asList(org.jooq.db.generate.Keys.USER_GAME_STATUS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.db.generate.tables.UserGameStatus as(java.lang.String alias) {
		return new org.jooq.db.generate.tables.UserGameStatus(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.jooq.db.generate.tables.UserGameStatus rename(java.lang.String name) {
		return new org.jooq.db.generate.tables.UserGameStatus(name, null);
	}
}
