/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersSteps extends org.jooq.impl.TableImpl<org.jooq.db.generate.tables.records.UsersStepsRecord> {

	private static final long serialVersionUID = 475104506;

	/**
	 * The singleton instance of <code>star_marines_bot.users_steps</code>
	 */
	public static final org.jooq.db.generate.tables.UsersSteps USERS_STEPS = new org.jooq.db.generate.tables.UsersSteps();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.db.generate.tables.records.UsersStepsRecord> getRecordType() {
		return org.jooq.db.generate.tables.records.UsersStepsRecord.class;
	}

	/**
	 * The column <code>star_marines_bot.users_steps.step_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.UsersStepsRecord, java.lang.Long> STEP_ID = createField("step_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>star_marines_bot.users_steps.from</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.UsersStepsRecord, java.lang.Long> FROM = createField("from", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>star_marines_bot.users_steps.to</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.UsersStepsRecord, java.lang.Long> TO = createField("to", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>star_marines_bot.users_steps.amount</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.UsersStepsRecord, java.lang.Integer> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>star_marines_bot.users_steps.user_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.UsersStepsRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>star_marines_bot.users_steps</code> table reference
	 */
	public UsersSteps() {
		this("users_steps", null);
	}

	/**
	 * Create an aliased <code>star_marines_bot.users_steps</code> table reference
	 */
	public UsersSteps(java.lang.String alias) {
		this(alias, org.jooq.db.generate.tables.UsersSteps.USERS_STEPS);
	}

	private UsersSteps(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.UsersStepsRecord> aliased) {
		this(alias, aliased, null);
	}

	private UsersSteps(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.UsersStepsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersStepsRecord> getPrimaryKey() {
		return org.jooq.db.generate.Keys.USERS_STEPS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersStepsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersStepsRecord>>asList(org.jooq.db.generate.Keys.USERS_STEPS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.jooq.db.generate.tables.records.UsersStepsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.jooq.db.generate.tables.records.UsersStepsRecord, ?>>asList(org.jooq.db.generate.Keys.USERS_STEPS__USERS_STEPS_FORM_FKEY, org.jooq.db.generate.Keys.USERS_STEPS__USERS_STEPS_TO_FKEY, org.jooq.db.generate.Keys.USERS_STEPS__USERS_STEPS_USER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.db.generate.tables.UsersSteps as(java.lang.String alias) {
		return new org.jooq.db.generate.tables.UsersSteps(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.jooq.db.generate.tables.UsersSteps rename(java.lang.String name) {
		return new org.jooq.db.generate.tables.UsersSteps(name, null);
	}
}
