/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends org.jooq.impl.TableImpl<org.jooq.db.generate.tables.records.UsersRecord> {

	private static final long serialVersionUID = 363930821;

	/**
	 * The singleton instance of <code>star_marines_bot.users</code>
	 */
	public static final org.jooq.db.generate.tables.Users USERS = new org.jooq.db.generate.tables.Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.db.generate.tables.records.UsersRecord> getRecordType() {
		return org.jooq.db.generate.tables.records.UsersRecord.class;
	}

	/**
	 * The column <code>star_marines_bot.users.user_id</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.UsersRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>star_marines_bot.users.login</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.UsersRecord, java.lang.String> LOGIN = createField("login", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>star_marines_bot.users.password</code>.
	 */
	public final org.jooq.TableField<org.jooq.db.generate.tables.records.UsersRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * Create a <code>star_marines_bot.users</code> table reference
	 */
	public Users() {
		this("users", null);
	}

	/**
	 * Create an aliased <code>star_marines_bot.users</code> table reference
	 */
	public Users(java.lang.String alias) {
		this(alias, org.jooq.db.generate.tables.Users.USERS);
	}

	private Users(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.UsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Users(java.lang.String alias, org.jooq.Table<org.jooq.db.generate.tables.records.UsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.jooq.db.generate.StarMarinesBot.STAR_MARINES_BOT, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersRecord> getPrimaryKey() {
		return org.jooq.db.generate.Keys.USER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.db.generate.tables.records.UsersRecord>>asList(org.jooq.db.generate.Keys.USER_PKEY, org.jooq.db.generate.Keys.USER_LOGIN_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.db.generate.tables.Users as(java.lang.String alias) {
		return new org.jooq.db.generate.tables.Users(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.jooq.db.generate.tables.Users rename(java.lang.String name) {
		return new org.jooq.db.generate.tables.Users(name, null);
	}
}
