/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamesUsersRecord extends org.jooq.impl.UpdatableRecordImpl<org.jooq.db.generate.tables.records.GamesUsersRecord> implements org.jooq.Record3<java.lang.Long, java.lang.Long, java.lang.Short> {

	private static final long serialVersionUID = 1896175202;

	/**
	 * Setter for <code>star_marines_bot.games_users.game_id</code>.
	 */
	public void setGameId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>star_marines_bot.games_users.game_id</code>.
	 */
	public java.lang.Long getGameId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>star_marines_bot.games_users.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>star_marines_bot.games_users.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>star_marines_bot.games_users.user_status_id</code>.
	 */
	public void setUserStatusId(java.lang.Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>star_marines_bot.games_users.user_status_id</code>.
	 */
	public java.lang.Short getUserStatusId() {
		return (java.lang.Short) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Short> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.Long, java.lang.Short> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.jooq.db.generate.tables.GamesUsers.GAMES_USERS.GAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return org.jooq.db.generate.tables.GamesUsers.GAMES_USERS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field3() {
		return org.jooq.db.generate.tables.GamesUsers.GAMES_USERS.USER_STATUS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getGameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value3() {
		return getUserStatusId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GamesUsersRecord value1(java.lang.Long value) {
		setGameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GamesUsersRecord value2(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GamesUsersRecord value3(java.lang.Short value) {
		setUserStatusId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GamesUsersRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Short value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GamesUsersRecord
	 */
	public GamesUsersRecord() {
		super(org.jooq.db.generate.tables.GamesUsers.GAMES_USERS);
	}

	/**
	 * Create a detached, initialised GamesUsersRecord
	 */
	public GamesUsersRecord(java.lang.Long gameId, java.lang.Long userId, java.lang.Short userStatusId) {
		super(org.jooq.db.generate.tables.GamesUsers.GAMES_USERS);

		setValue(0, gameId);
		setValue(1, userId);
		setValue(2, userStatusId);
	}
}
