/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamesRecord extends org.jooq.impl.UpdatableRecordImpl<org.jooq.db.generate.tables.records.GamesRecord> implements org.jooq.Record3<java.lang.Long, java.lang.String, java.lang.Short> {

	private static final long serialVersionUID = -180529212;

	/**
	 * Setter for <code>star_marines_bot.games.game_id</code>.
	 */
	public void setGameId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>star_marines_bot.games.game_id</code>.
	 */
	public java.lang.Long getGameId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>star_marines_bot.games.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>star_marines_bot.games.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>star_marines_bot.games.game_status_id</code>.
	 */
	public void setGameStatusId(java.lang.Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>star_marines_bot.games.game_status_id</code>.
	 */
	public java.lang.Short getGameStatusId() {
		return (java.lang.Short) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Short> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Long, java.lang.String, java.lang.Short> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.jooq.db.generate.tables.Games.GAMES.GAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.jooq.db.generate.tables.Games.GAMES.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field3() {
		return org.jooq.db.generate.tables.Games.GAMES.GAME_STATUS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getGameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value3() {
		return getGameStatusId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GamesRecord value1(java.lang.Long value) {
		setGameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GamesRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GamesRecord value3(java.lang.Short value) {
		setGameStatusId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GamesRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Short value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GamesRecord
	 */
	public GamesRecord() {
		super(org.jooq.db.generate.tables.Games.GAMES);
	}

	/**
	 * Create a detached, initialised GamesRecord
	 */
	public GamesRecord(java.lang.Long gameId, java.lang.String title, java.lang.Short gameStatusId) {
		super(org.jooq.db.generate.tables.Games.GAMES);

		setValue(0, gameId);
		setValue(1, title);
		setValue(2, gameStatusId);
	}
}
