/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameStatusRecord extends org.jooq.impl.UpdatableRecordImpl<org.jooq.db.generate.tables.records.GameStatusRecord> implements org.jooq.Record2<java.lang.Short, java.lang.String> {

	private static final long serialVersionUID = -946732229;

	/**
	 * Setter for <code>star_marines_bot.game_status.game_status_id</code>.
	 */
	public void setGameStatusId(java.lang.Short value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>star_marines_bot.game_status.game_status_id</code>.
	 */
	public java.lang.Short getGameStatusId() {
		return (java.lang.Short) getValue(0);
	}

	/**
	 * Setter for <code>star_marines_bot.game_status.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>star_marines_bot.game_status.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Short> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Short, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Short, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field1() {
		return org.jooq.db.generate.tables.GameStatus.GAME_STATUS.GAME_STATUS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.jooq.db.generate.tables.GameStatus.GAME_STATUS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value1() {
		return getGameStatusId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameStatusRecord value1(java.lang.Short value) {
		setGameStatusId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameStatusRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameStatusRecord values(java.lang.Short value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GameStatusRecord
	 */
	public GameStatusRecord() {
		super(org.jooq.db.generate.tables.GameStatus.GAME_STATUS);
	}

	/**
	 * Create a detached, initialised GameStatusRecord
	 */
	public GameStatusRecord(java.lang.Short gameStatusId, java.lang.String title) {
		super(org.jooq.db.generate.tables.GameStatus.GAME_STATUS);

		setValue(0, gameStatusId);
		setValue(1, title);
	}
}
