/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetsRecord extends org.jooq.impl.UpdatableRecordImpl<org.jooq.db.generate.tables.records.PlanetsRecord> implements org.jooq.Record5<java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = -1000000933;

	/**
	 * Setter for <code>star_marines_bot.planets.planet_id</code>.
	 */
	public void setPlanetId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>star_marines_bot.planets.planet_id</code>.
	 */
	public java.lang.Long getPlanetId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>star_marines_bot.planets.units</code>.
	 */
	public void setUnits(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>star_marines_bot.planets.units</code>.
	 */
	public java.lang.Integer getUnits() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>star_marines_bot.planets.max_units</code>.
	 */
	public void setMaxUnits(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>star_marines_bot.planets.max_units</code>.
	 */
	public java.lang.Integer getMaxUnits() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>star_marines_bot.planets.owner_id</code>.
	 */
	public void setOwnerId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>star_marines_bot.planets.owner_id</code>.
	 */
	public java.lang.Long getOwnerId() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>star_marines_bot.planets.game_id</code>.
	 */
	public void setGameId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>star_marines_bot.planets.game_id</code>.
	 */
	public java.lang.Long getGameId() {
		return (java.lang.Long) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Integer, java.lang.Integer, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.jooq.db.generate.tables.Planets.PLANETS.PLANET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.jooq.db.generate.tables.Planets.PLANETS.UNITS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.jooq.db.generate.tables.Planets.PLANETS.MAX_UNITS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return org.jooq.db.generate.tables.Planets.PLANETS.OWNER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return org.jooq.db.generate.tables.Planets.PLANETS.GAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getPlanetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getUnits();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getMaxUnits();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getOwnerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getGameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRecord value1(java.lang.Long value) {
		setPlanetId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRecord value2(java.lang.Integer value) {
		setUnits(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRecord value3(java.lang.Integer value) {
		setMaxUnits(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRecord value4(java.lang.Long value) {
		setOwnerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRecord value5(java.lang.Long value) {
		setGameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRecord values(java.lang.Long value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Long value4, java.lang.Long value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlanetsRecord
	 */
	public PlanetsRecord() {
		super(org.jooq.db.generate.tables.Planets.PLANETS);
	}

	/**
	 * Create a detached, initialised PlanetsRecord
	 */
	public PlanetsRecord(java.lang.Long planetId, java.lang.Integer units, java.lang.Integer maxUnits, java.lang.Long ownerId, java.lang.Long gameId) {
		super(org.jooq.db.generate.tables.Planets.PLANETS);

		setValue(0, planetId);
		setValue(1, units);
		setValue(2, maxUnits);
		setValue(3, ownerId);
		setValue(4, gameId);
	}
}
