/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetsRelationsRecord extends org.jooq.impl.UpdatableRecordImpl<org.jooq.db.generate.tables.records.PlanetsRelationsRecord> implements org.jooq.Record4<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 2015235914;

	/**
	 * Setter for <code>star_marines_bot.planets_relations.relation_id</code>.
	 */
	public void setRelationId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>star_marines_bot.planets_relations.relation_id</code>.
	 */
	public java.lang.Long getRelationId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>star_marines_bot.planets_relations.ancestor_id</code>.
	 */
	public void setAncestorId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>star_marines_bot.planets_relations.ancestor_id</code>.
	 */
	public java.lang.Long getAncestorId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>star_marines_bot.planets_relations.descendant_id</code>.
	 */
	public void setDescendantId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>star_marines_bot.planets_relations.descendant_id</code>.
	 */
	public java.lang.Long getDescendantId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>star_marines_bot.planets_relations.game_id</code>.
	 */
	public void setGameId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>star_marines_bot.planets_relations.game_id</code>.
	 */
	public java.lang.Long getGameId() {
		return (java.lang.Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS.RELATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS.ANCESTOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS.DESCENDANT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS.GAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getRelationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getAncestorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getDescendantId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getGameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRelationsRecord value1(java.lang.Long value) {
		setRelationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRelationsRecord value2(java.lang.Long value) {
		setAncestorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRelationsRecord value3(java.lang.Long value) {
		setDescendantId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRelationsRecord value4(java.lang.Long value) {
		setGameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlanetsRelationsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3, java.lang.Long value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlanetsRelationsRecord
	 */
	public PlanetsRelationsRecord() {
		super(org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS);
	}

	/**
	 * Create a detached, initialised PlanetsRelationsRecord
	 */
	public PlanetsRelationsRecord(java.lang.Long relationId, java.lang.Long ancestorId, java.lang.Long descendantId, java.lang.Long gameId) {
		super(org.jooq.db.generate.tables.PlanetsRelations.PLANETS_RELATIONS);

		setValue(0, relationId);
		setValue(1, ancestorId);
		setValue(2, descendantId);
		setValue(3, gameId);
	}
}
