/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersStepsRecord extends org.jooq.impl.UpdatableRecordImpl<org.jooq.db.generate.tables.records.UsersStepsRecord> implements org.jooq.Record5<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Long> {

	private static final long serialVersionUID = -128832232;

	/**
	 * Setter for <code>star_marines_bot.users_steps.step_id</code>.
	 */
	public void setStepId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>star_marines_bot.users_steps.step_id</code>.
	 */
	public java.lang.Long getStepId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>star_marines_bot.users_steps.from</code>.
	 */
	public void setFrom(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>star_marines_bot.users_steps.from</code>.
	 */
	public java.lang.Long getFrom() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>star_marines_bot.users_steps.to</code>.
	 */
	public void setTo(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>star_marines_bot.users_steps.to</code>.
	 */
	public java.lang.Long getTo() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>star_marines_bot.users_steps.amount</code>.
	 */
	public void setAmount(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>star_marines_bot.users_steps.amount</code>.
	 */
	public java.lang.Integer getAmount() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>star_marines_bot.users_steps.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>star_marines_bot.users_steps.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Long> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.Long> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.jooq.db.generate.tables.UsersSteps.USERS_STEPS.STEP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return org.jooq.db.generate.tables.UsersSteps.USERS_STEPS.FROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return org.jooq.db.generate.tables.UsersSteps.USERS_STEPS.TO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.jooq.db.generate.tables.UsersSteps.USERS_STEPS.AMOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return org.jooq.db.generate.tables.UsersSteps.USERS_STEPS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getStepId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getFrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getTo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getAmount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersStepsRecord value1(java.lang.Long value) {
		setStepId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersStepsRecord value2(java.lang.Long value) {
		setFrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersStepsRecord value3(java.lang.Long value) {
		setTo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersStepsRecord value4(java.lang.Integer value) {
		setAmount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersStepsRecord value5(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersStepsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3, java.lang.Integer value4, java.lang.Long value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersStepsRecord
	 */
	public UsersStepsRecord() {
		super(org.jooq.db.generate.tables.UsersSteps.USERS_STEPS);
	}

	/**
	 * Create a detached, initialised UsersStepsRecord
	 */
	public UsersStepsRecord(java.lang.Long stepId, java.lang.Long from, java.lang.Long to, java.lang.Integer amount, java.lang.Long userId) {
		super(org.jooq.db.generate.tables.UsersSteps.USERS_STEPS);

		setValue(0, stepId);
		setValue(1, from);
		setValue(2, to);
		setValue(3, amount);
		setValue(4, userId);
	}
}
