/**
 * This class is generated by jOOQ
 */
package org.jooq.db.generate.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGameStatusRecord extends org.jooq.impl.UpdatableRecordImpl<org.jooq.db.generate.tables.records.UserGameStatusRecord> implements org.jooq.Record2<java.lang.Short, java.lang.String> {

	private static final long serialVersionUID = 944349497;

	/**
	 * Setter for <code>star_marines_bot.user_game_status.user_status_id</code>.
	 */
	public void setUserStatusId(java.lang.Short value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>star_marines_bot.user_game_status.user_status_id</code>.
	 */
	public java.lang.Short getUserStatusId() {
		return (java.lang.Short) getValue(0);
	}

	/**
	 * Setter for <code>star_marines_bot.user_game_status.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>star_marines_bot.user_game_status.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Short> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Short, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Short, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field1() {
		return org.jooq.db.generate.tables.UserGameStatus.USER_GAME_STATUS.USER_STATUS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.jooq.db.generate.tables.UserGameStatus.USER_GAME_STATUS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value1() {
		return getUserStatusId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserGameStatusRecord value1(java.lang.Short value) {
		setUserStatusId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserGameStatusRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserGameStatusRecord values(java.lang.Short value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserGameStatusRecord
	 */
	public UserGameStatusRecord() {
		super(org.jooq.db.generate.tables.UserGameStatus.USER_GAME_STATUS);
	}

	/**
	 * Create a detached, initialised UserGameStatusRecord
	 */
	public UserGameStatusRecord(java.lang.Short userStatusId, java.lang.String title) {
		super(org.jooq.db.generate.tables.UserGameStatus.USER_GAME_STATUS);

		setValue(0, userStatusId);
		setValue(1, title);
	}
}
